### PR TITLE
added favicon, split html into 2 docs, renamed css files, changed the…

### PR DESCRIPTION
**Pull request by vinson-ridenour**
… transition method between search and results page

### CODE REVIEW

**Comment by jhuynh85** [comment]
Is there a reason you renamed `app.js` to `app2.js`?

**Comment by vinson-ridenour** [comment]
I was working with new versions and forgot to rename that one back to app.js.

**Comment by jhuynh85** [comment]
Can you also remove `yelp.js`? It was originally for our Yelp API functions but we're no longer using it so it's not needed.

**Comment by vinson-ridenour** [comment]
No prob - removed!

**Comment by jhuynh85** [comment]
Haha, I'm going to leave this PR open til tomorrow in case you find any other changes you want to push

**Comment by vinson-ridenour** [comment]
Oh I'm done for the night. See ya tomorrow

**Pull request merged**
